//
// Created by HP on 05/11/2025.
//

#ifndef AIRPLANEMANAGER_FLIGHTSTATUS_H
#define AIRPLANEMANAGER_FLIGHTSTATUS_H


enum class FlightStatus {
    CANCELLED = 0,
    AVAILABLE = 1,
    SOLD_OUT = 2,
    COMPLETED = 3
};


#endif //AIRPLANEMANAGER_FLIGHTSTATUS_H